In [24]:
import pandas as pd
import numpy as np
import yfinance as yf
from pathlib import Path
from config import *

In [25]:
folders = [
    "data/raw",
    "data/processed",
    "data/cache",
    "figures",
    "results"
]

for folder in folders:
    Path(folder).mkdir(parents=True, exist_ok=True)

In [52]:
url = "https://raw.githubusercontent.com/datasets/s-and-p-500-companies/master/data/constituents.csv"

sp500 = pd.read_csv(url)
sp500.head()

,Symbol,Security,GICS Sector,GICS Sub-Industry,Headquarters Location,Date added,CIK,Founded
0,MMM,3M,Industrials,Industrial Conglomerates,"Saint Paul, Minnesota",1957-03-04,66740,1902
1,AOS,A. O. Smith,Industrials,Building Products,"Milwaukee, Wisconsin",2017-07-26,91142,1916
2,ABT,Abbott Laboratories,Health Care,Health Care Equipment,"North Chicago, Illinois",1957-03-04,1800,1888
3,ABBV,AbbVie,Health Care,Biotechnology,"North Chicago, Illinois",2012-12-31,1551152,2013 (1888)
4,ACN,Accenture,Information Technology,IT Consulting & Other Services,"Dublin, Ireland",2011-07-06,1467373,1989

In [53]:
tickers = sp500["Symbol"].tolist()
tickers = [ticker.replace(".","-") for ticker in tickers]

In [54]:
data = yf.download(
    tickers = tickers,
    start = START_DATE,
    end = END_DATE,
    auto_adjust = AUTO_ADJUST,
    progress = True)

[****************      34%                       ]  171 of 503 completed$FDXF: possibly delisted; no price data found  (1d 2016-01-01 -> 2026-01-01) (Yahoo error = "Data doesn't exist for startDate = 1451624400, endDate = 1767243600")
[**********************60%****                   ]  302 of 503 completed$HONA: possibly delisted; no price data found  (1d 2016-01-01 -> 2026-01-01) (Yahoo error = "Data doesn't exist for startDate = 1451624400, endDate = 1767243600")
[*********************100%***********************]  503 of 503 completed

2 Failed downloads:
['FDXF', 'HONA']: possibly delisted; no price data found  (1d 2016-01-01 -> 2026-01-01) (Yahoo error = "Data doesn't exist for startDate = 1451624400, endDate = 1767243600")

In [55]:
data.head()

Price      Adj Close           Close                                        \
Ticker          FDXF HONA          A       AAPL       ABBV ABNB        ABT
Date
2016-01-04       NaN  NaN  37.411743  23.709103  37.132977  NaN  34.910656
2016-01-05       NaN  NaN  37.283020  23.114971  36.978275  NaN  34.902508
2016-01-06       NaN  NaN  37.448521  22.662619  36.984726  NaN  34.609756
2016-01-07       NaN  NaN  35.857895  21.706150  36.875149  NaN  33.780300
2016-01-08       NaN  NaN  35.480923  21.820929  35.869648  NaN  33.072830

Price                                        ...   Volume                    \
Ticker           ACGL        ACN       ADBE  ...       WY     WYNN      XEL
Date                                         ...
2016-01-04  21.823122  85.188744  91.970001  ...  3556800  4249800  2819300
2016-01-05  21.902363  85.632111  92.339996  ...  2722800  4286100  2141200
2016-01-06  21.937229  85.464798  91.019997  ...  4843200  3316100  5191900
2016-01-07  21.915041  82.955055  89.110001  ...  4917400  5525600  5212200
2016-01-08  21.686827  82.151955  87.849998  ...  5022600  5740000  3005400

Price
Ticker           XOM      XYL      XYZ       YUM      ZBH     ZBRA      ZTS
Date
2016-01-04  20400100  1353400  2751500   4821623  2104084   656200  2871700
2016-01-05  11993500  1075400  2352800   5273420  2294737   611300  3116700
2016-01-06  18826900  1866000  1850600   5049330  2751233   881900  4670500
2016-01-07  21263800  1555400  1636000  11005453  1829589  1210600  4324400
2016-01-08  19033600  1471500   587300   5996184  1670969  1034700  4946100

[5 rows x 2517 columns]

In [56]:
prices = data["Close"]
prices.shape

(2514, 503)

In [57]:
report = pd.DataFrame({
    "Missing Values": prices.isna().sum(),
    "Missing %": prices.isna().mean()})

report.sort_values("Missing %", ascending = False)

        Missing Values  Missing %
Ticker
HONA              2514   1.000000
FDXF              2514   1.000000
Q                 2468   0.981702
SNDK              2292   0.911695
GEV               2071   0.823787
...                ...        ...
AJG                  0   0.000000
AKAM                 0   0.000000
ALB                  0   0.000000
ALGN                 0   0.000000
WMB                  0   0.000000

[503 rows x 2 columns]

In [58]:
valid = report["Missing %"] < MAX_MISSING_PCT

prices = prices.loc[:, valid]

In [59]:
prices.shape

(2514, 466)

In [60]:
prices = prices.ffill()

In [62]:
assert prices.isna().sum().sum() == 0

In [64]:
prices.to_parquet("data/processed/prices.parquet")

In [65]:
print("="*50)
print("MARKET DATA REPORT")
print("="*50)

print(f"Observations : {len(prices):,}")
print(f"Stocks       : {prices.shape[1]}")
print(f"Start        : {prices.index.min().date()}")
print(f"End          : {prices.index.max().date()}")

print("="*50)

==================================================
MARKET DATA REPORT
==================================================
Observations : 2,514
Stocks       : 466
Start        : 2016-01-04
End          : 2025-12-31
==================================================

In [66]:
print(type(prices))
prices.head()

<class 'pandas.core.frame.DataFrame'>

Ticker,A,AAPL,ABBV,ABT,ACGL,ACN,ADBE,ADI,ADM,ADP,...,WY,WYNN,XEL,XOM,XYL,XYZ,YUM,ZBH,ZBRA,ZTS
Date,,,,,,,,,,,,,,,,,,,,,
2016-01-04,37.411743,23.709103,37.132977,34.910656,21.823122,85.188744,91.970001,44.413136,26.224855,65.143188,...,19.850576,60.251110,25.832743,49.319607,31.682487,12.16,42.666485,90.639236,66.489998,43.027435
2016-01-05,37.283020,23.114971,36.978275,34.902508,21.902363,85.632111,92.339996,44.086819,26.517542,65.301949,...,19.897156,61.390095,26.093248,49.739841,31.673697,11.51,42.560143,92.526627,64.820000,43.701015
2016-01-06,37.448521,22.662619,36.984726,34.609756,21.937229,85.464798,91.019997,42.210438,25.873627,64.500267,...,19.457956,58.209755,26.368221,49.325974,31.278545,11.52,42.258793,92.927261,62.230000,43.710125
2016-01-07,35.857895,21.706150,36.875149,33.780300,21.915041,82.955055,89.110001,41.133545,25.258982,62.531742,...,18.739262,52.733967,26.469524,48.536469,30.470688,11.16,40.817070,90.790596,59.410000,42.381161
2016-01-08,35.480923,21.820929,35.869648,33.072830,21.686827,82.151955,87.849998,40.774586,25.163855,62.015816,...,18.566242,50.587463,26.180079,47.555931,30.180899,11.31,40.261654,90.407753,59.250000,41.762184